### ISSUE TITLE
Beds/Boats not showing in correct place.

### ISSUE THREAD

**Issue by iaidan** [GrapeshotGames/AtlasMapViewer#1]
Hi,

It looks like the beds/boats aren't being adjusted into place correct, I plan on looking into why but don't have the time just now.

![image](https://user-images.githubusercontent.com/946333/51094089-e0311f80-17a1-11e9-8202-cfc13be6ec2b.png)

**Comment by upperking** [comment]
same here, tried it on several machines through their browsers.
![offgrid](https://user-images.githubusercontent.com/9461535/51138695-c75f5300-180f-11e9-8014-46834488ba90.png)

**Comment by sakurasammi** [comment]
Your server grid size is set incorrectly

**Comment by iaidan** [comment]
I can assure you it isnt, it's set on 3x3.

const config = {
    ServersX: 3,
    ServersY: 3,
    Suggestions: [
        "spawnshipfast name",
        "spawnbed name",
        "destroyall",
    ]
}

**Comment by iaidan** [comment]
Here's the other config:


{
    "Host": "",
    "Port": 0,
    "TerritoryURL": "http://localhost:0/territoryTiles/",
    "StaticDir": "./www",
    "FetchRateInSeconds": 30,
    "DisableCommands": true,
    "RedisAddress": "127.0.0.1:0",
    "RedisPassword": "7505C6QVlm",
    "RedisDB": 0
}

**Comment by smooreace** [comment]
When was the last time you updated your tools? Youre welcome!

**Comment by GrapeshotGames** [comment]
After you changed that to 3x3 did you restart the binary? I've found that go can cache some things pretty well. So do that and also clear your browser cache to see if it gets all better. It does look like the values aren't set but I'm guessing it's a caching change. Hope this helps!

**Comment by sakurasammi** [comment]
> I can assure you it isnt, it's set on 3x3.
> 
> const config = {
> ServersX: 3,
> ServersY: 3,
> Suggestions: [
> "spawnshipfast name",
> "spawnbed name",
> "destroyall",
> ]
> }

You also need to change it in the config.js in the www folder

**Comment by iaidan** [comment]
I updated it, seemed to fix their positions.

It's not very well done for the beds and boats, zoom doesn't affect them.

This can be closed.

**Comment by LordZardeck** [comment]
This appears to still be a problem. Downloaded today, ships are offset. Tried using the servers x,y settings in config, no difference. Source code doesn't seem to use those settings anyway:

![image](https://user-images.githubusercontent.com/1145989/52516764-b37ff480-2bf5-11e9-89fc-5289fd5db5df.png)
