### ISSUE TITLE
tribe claims not showing

### ISSUE THREAD

**Issue by erall0** [GrapeshotGames/AtlasMapViewer#3]
I cant get the tribe claims to show up with the boats and beds like u have in your guide what am I doing wrong?

thanks

**Comment by GrapeshotGames** [comment]
Tribe claims come from https://github.com/GrapeshotGames/AtlasTerritoryMap be sure that is working in game and that your map viewer is not only pointing at it but has the option mentioned to generate the title images.

**Comment by GrapeshotGames** [comment]
I'm gonna assume you got this working since no more after a few days :)  Cheers!
