### ISSUE TITLE
Entity 4254671928 references parent 688817604 that does not exist, removing from list

### ISSUE THREAD

**Issue by Shainara** [GrapeshotGames/AtlasMapViewer#4]
Hello. How to fix this error?

2019/01/28 05:39:23 Listening on  185.66.84.210:8880
2019/01/28 05:39:23 Redis scan took 3.9881ms
2019/01/28 05:39:23 Redis scan took 6.9813ms
2019/01/28 05:39:23 Entity 4254671928 references parent 688817604 that does not exist, removing from list
2019/01/28 05:39:23 Entity 3324557960 references parent 2412120522 that does not exist, removing from list
2019/01/28 05:39:23 Entity 764811794 references parent 4257052223 that does not exist, removing from list
2019/01/28 05:39:23 Entity 1339362368 references parent 1779182362 that does not exist, removing from list
2019/01/28 05:39:23 Entity 1229764135 references parent 4257052223 that does not exist, removing from list

**Comment by smooreace** [comment]
Server errors have nothing to do with a map editor

**Comment by Shainara** [comment]
I found how to fix these errors. Now AtlasMapViewer works correctly, but it shows a blank page in the browser, as if the port is closed. Last week everything worked correctly and the settings did not change.

**Comment by Foppa01** [comment]
> I found how to fix these errors. Now AtlasMapViewer works correctly, but it shows a blank page in the browser, as if the port is closed. Last week everything worked correctly and the settings did not change.

I have the same issue.

**Comment by smooreace** [comment]
The best place to start in fixing issues with the territory map and the map viewer is to delete it all and start fresh! Not sure if an issue develops and get stuck deep inside the process or what, but I've had several people have various issues. A fresh start always solved it.

**Comment by whiterober** [comment]
> I found how to fix these errors. Now AtlasMapViewer works correctly, but it shows a blank page in the browser, as if the port is closed. Last week everything worked correctly and the settings did not change.

Can you tell me How did you fix these errors?

**Comment by Shainara** [comment]
> > I found how to fix these errors. Now AtlasMapViewer works correctly, but it shows a blank page in the browser, as if the port is closed. Last week everything worked correctly and the settings did not change.
> 
> Can you tell me How did you fix these errors?

Redis Desktop Manager

**Comment by sakurasammi** [comment]
> The best place to start in fixing issues with the territory map and the map viewer is to delete it all and start fresh! Not sure if an issue develops and get stuck deep inside the process or what, but I've had several people have various issues. A fresh start always solved it.

Stop offering useless replies. All your solutions are for people to wipe their data. People rather fix the issue than wiping every time something comes up. Do yourself a favor and quit trolling these forums.

**Comment by smooreace** [comment]
No pea-brain... it doesn't WIPE anything except a screwed up config file.
Know what you're talking about before you engage your face!

**Comment by Shainara** [comment]
In fact, the problem with displaying the map in the browser was not due to launch errors. The page has been blocked by the provider.

But thanks to this, I figured out how to work with redis database files.

**Comment by GrapeshotGames** [comment]
Hey @Shainara ! Looks like you got it working for now? I'm assuming you just deleted those tribe entities in Redis? If someone wants to change this to throw out things it thinks are invalid entries I will happily take that PR. What concerns me more though is if you have a way to reproduce getting that bad entry in the first place in game? Not it already being broken but some way to get it from scratch or how to even just generate new ones would be helpful in that we can try to figure out what went wrong.
