### ISSUE TITLE
Display selected ship's path

### ISSUE THREAD

**Issue by ivodopyanov** [GrapeshotGames/AtlasMapViewer#8]
Looking through the mapviewer.js file, I've noticed shipPath variable and that almost everything is in place for it except rendering. Can you implement it?

**Comment by smooreace** [comment]
Its more about what YOU implement. Its up to you to build a map that provides the data you want displayed. Perhaps this should be made more clear but @GrapeshotGames

**Comment by ivodopyanov** [comment]
OK, thanks. Sorry for bothering.
